import { Montserrat } from "@/libs/fonts";
import "./global.scss";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { client } from "@/libs/sanity";
import { contactQuery, settingsQuery } from "@/libs/sanityQueries";

export const metadata = {
  title: "NK home and decor",
  description: "Generated by create next app",
};

export const revalidate = 60;

export default async function RootLayout({ children }) {
  let contactData = null;
  let settingsData = null;
  
  try {
    if (process.env.NEXT_PUBLIC_SANITY_PROJECT_ID) {
      [contactData, settingsData] = await Promise.all([
        client.fetch(contactQuery),
        client.fetch(settingsQuery)
      ]);
    }
  } catch (error) {
    console.error("Error fetching layout data from Sanity:", error);
  }

  return (
    <html lang="en">
      <body
        className={`${Montserrat.variable} antialiased`}
      >
        <Header contact={contactData} settings={settingsData} />
        <main>{children}</main>
        <Footer contact={contactData} settings={settingsData} />
      </body>
    </html>
  );
}
