import { Montserrat } from "@/libs/fonts";
import "./globals.scss";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";


export const metadata = {
  title: "NK home and decor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Montserrat.variable} antialiased`}
      >
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
